spring.application.name=PP12Serveris

server.port=8088
spring.datasource.url=jdbc:postgresql://localhost:5432/pp12database
spring.datasource.username=kristaps
spring.datasource.password=bistamais92
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB